branch-defaults:
  master:
    environment: env-production
    group_suffix: null
global:
  application_name: hello-ci-workflow
  default_ec2_keyname: aws-eb4
  default_platform: Docker 1.11.2
  default_region: ap-northeast-1
  profile: null
  sc: git
